<?php

/**
 * @file
 * Contains protected_pages_scheduler.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_form_alter().
 */
function protected_pages_scheduler_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'protected_pages_edit_form'|| $form_id == 'protected_pages_add_form') {
    $remove_time = NULL;
    $pid = $form['rules_list']['pid']['#value'] ?? NULL;
    if ($pid) {
      $fields = ['remove_time'];
      $conditions = [];
      $conditions['general'][] = [
        'field' => 'pid',
        'value' => $pid,
        'operator' => '=',
      ];
      $remove_time = \Drupal::service('protected_pages.storage')->loadProtectedPage($fields, $conditions, TRUE);
    }
    $form['rules_list']['remove_time'] = [
      '#type' => 'datetime',
      '#title' => t('Automatically remove password on'),
      '#default_value' => $remove_time ? DrupalDateTime::createFromTimestamp($remove_time) : NULL,
      '#description' => t('Date and time when the password protection is automatically removed.<br/><strong>Important:</strong> Password removal might be delayed depending how often CRON jobs are scheduled (i.e. for up to a minute accuracy, CRON must run every minute). Also, the seconds are irrelevant.'),
      '#weight' => 10,
    ];
    $form['rules_list']['submit']['#weight'] = 20;
    $form['#submit'][] = 'protected_pages_scheduler_form_submit';
  }
}

/**
 * Save remove time.
 */
function protected_pages_scheduler_form_submit(&$form, FormStateInterface $form_state) {
  $page_data = [];
  $page_data['remove_time'] = $form_state->getValue('remove_time') ? $form_state->getValue('remove_time')->getTimestamp() : NULL;
  if (!$pid = $form_state->getValue('pid')) {
    $conditions = [];
    $conditions['general'][] = [
      'field' => 'path',
      'value' => Html::escape($form_state->getValue('path')),
      'operator' => '=',
    ];
    $fields = ['pid'];
    $pid = \Drupal::service('protected_pages.storage')->loadProtectedPage($fields, $conditions, TRUE);
  }
  \Drupal::service('protected_pages.storage')->updateProtectedPage($page_data, $pid);
}

/**
 * Implements hook_cron().
 */
function protected_pages_scheduler_cron() {
  $protected_pages_storage = \Drupal::service('protected_pages.storage');
  $time = \Drupal::service('datetime.time');

  $conditions = [];
  $conditions['general'][] = [
    'field' => 'remove_time',
    'value' => $time->getRequestTime(),
    'operator' => '<=',
  ];
  $rows = $protected_pages_storage->loadProtectedPage([], $conditions);
  foreach ($rows as $row) {
    \Drupal::logger('protected_pages_scheduler')->info(
      'Removing password protection according to schedule for page @path (pid: @eid)',
      ['@eid' => $row->pid, '@path' => $row->path]
    );
    $protected_pages_storage->deleteProtectedPage($row->pid);
  }
  if ($rows) {
    drupal_flush_all_caches();
  }

}

/**
 * Implements hook_protected_pages_alter_listing().
 */
function protected_pages_scheduler_protected_pages_alter_listing(&$headers, &$rows, $pages) {
  // Add before last column which is 'Operations'.
  $index = count($headers) - 1;
  $headers = array_merge(
    array_slice($headers, 0, $index),
    [new TranslatableMarkup('Protected until')],
    array_slice($headers, $index)
  );
  foreach ($pages as $i => $page) {
    if ($page->remove_time) {
      $protected_until = \Drupal::service('date.formatter')->format($page->remove_time, 'custom', 'j M Y - H:i');
    }
    else {
      $protected_until = new TranslatableMarkup('Forever');
    }
    $rows[$i]['data'] = array_merge(
      array_slice($rows[$i]['data'], 0, $index),
      [$protected_until],
      array_slice($rows[$i]['data'], $index)
    );
  }
}
