<?php

/**
 * @file
 * Install and uninstall functions for the protected_pages_scheduler module.
 */

/**
 * Implements hook_install().
 */
function protected_pages_scheduler_install() {
  $schema = \Drupal::database()->schema();
  if (!$schema->fieldExists('protected_pages', 'remove_time')) {
    $schema->addField('protected_pages', 'remove_time', [
      'description' => '',
      'type' => 'int',
      'default' => NULL,
    ]);
  }
}

/**
 * Implements hook_uninstall().
 */
function protected_pages_scheduler_uninstall() {
  $schema = \Drupal::database()->schema();
  if ($schema->fieldExists('protected_pages', 'remove_time')) {
    $schema->dropField('protected_pages', 'remove_time');
  }
}
